Turn all private to internal, all methods to virtual
TelediskoDAO/contracts-legacy pull request #71
Opened 2022-06-29 10:31 UTC by sirnicolaz

As per title.

2022-06-29 11:22 UTC, sirnicolaz commented
I have also checked if there is any big change in the deployment gas cost due to this change. The worst case is Voting with 24 gas of difference. ResolutionManager and ShareholderRegistry have absolutely no difference.

2022-06-29 11:47 UTC, sirnicolaz commented
Out of curiosity, I had a look at the opcode generated for the different variations of public/internal/private virtual/non virtual using a dummy contract.

For variables, che most concise opcode comes with `internal` variables, followed by `private` and `public` (not a surprise, as it generates the getter function). For a contract containing just a `uint256`, the result is the following:
```
private
PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x0 DUP1 REVERT INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 0xE2 PUSH1 0x90 0xEB 0xDD 0x23 EQ CALLDATASIZE 0xAF SWAP3 0xAF DUP16 PUSH10 0xD2E048DDEDF8ABFFC93C 0xE3 0xC2 COINBASE 0x1E DUP6 LOG1 ADD LOG2 LT PUSH5 0x736F6C6343 STOP ADDMOD SMOD STOP CALLER

internal
PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x0 DUP1 REVERT INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 PUSH26 0x34FBD6206A528E47603FECB49B73E519FAECF4057BAC8D2296FB 0xEC SWAP7 LOG4 DUP12 PUSH12 0x64736F6C6343000807003300

public
PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH1 0xF JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x4 CALLDATASIZE LT PUSH1 0x28 JUMPI PUSH1 0x0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0x8381F58A EQ PUSH1 0x2D JUMPI JUMPDEST PUSH1 0x0 DUP1 REVERT JUMPDEST PUSH1 0x33 PUSH1 0x47 JUMP JUMPDEST PUSH1 0x40 MLOAD PUSH1 0x3E SWAP2 SWAP1 PUSH1 0x5A JUMP JUMPDEST PUSH1 0x40 MLOAD DUP1 SWAP2 SUB SWAP1 RETURN JUMPDEST PUSH1 0x0 SLOAD DUP2 JUMP JUMPDEST PUSH1 0x54 DUP2 PUSH1 0x73 JUMP JUMPDEST DUP3 MSTORE POP POP JUMP JUMPDEST PUSH1 0x0 PUSH1 0x20 DUP3 ADD SWAP1 POP PUSH1 0x6D PUSH1 0x0 DUP4 ADD DUP5 PUSH1 0x4D JUMP JUMPDEST SWAP3 SWAP2 POP POP JUMP JUMPDEST PUSH1 0x0 DUP2 SWAP1 POP SWAP2 SWAP1 POP JUMP INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 PUSH20 0xFF1CAFF543D3D3DDCE513B919B6A4FC7186A3EFD 0xCA 0xB2 SWAP8 CODECOPY DUP8 0x22 0xEE DUP9 0xE4 MUL JUMPI PUSH5 0x736F6C6343 STOP ADDMOD SMOD STOP CALLER
```

When it comes to functions, virtual functions come with some additional opcodes. The difference between `public` and `internal` is noticeable. `internal` seems to have less ops than `private`. For a contract containing just a function called `test` doing nothing, the result is the following:

```
public
PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH1 0xF JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x4 CALLDATASIZE LT PUSH1 0x28 JUMPI PUSH1 0x0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0xF8A8FD6D EQ PUSH1 0x2D JUMPI JUMPDEST PUSH1 0x0 DUP1 REVERT JUMPDEST PUSH1 0x33 PUSH1 0x35 JUMP JUMPDEST STOP JUMPDEST JUMP INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 0xB3 CALLDATASIZE 0xDB 0xF DUP2 SWAP1 SELFDESTRUCT LOG1 PUSH30 0x3A73501BC9753FAF8159D885F5E43E3DEC007D811BD0A764736F6C634300 ADDMOD SMOD STOP CALLER

public virtual
PUSH1 0x80 PUSH1 0x40 MSTORE CALLVALUE DUP1 ISZERO PUSH1 0xF JUMPI PUSH1 0x0 DUP1 REVERT JUMPDEST POP PUSH1 0x4 CALLDATASIZE LT PUSH1 0x28 JUMPI PUSH1 0x0 CALLDATALOAD PUSH1 0xE0 SHR DUP1 PUSH4 0xF8A8FD6D EQ PUSH1 0x2D JUMPI JUMPDEST PUSH1 0x0 DUP1 REVERT JUMPDEST PUSH1 0x33 PUSH1 0x35 JUMP JUMPDEST STOP JUMPDEST JUMP INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 PUSH4 0x84187C4C 0x24 0xD6 PUSH24 0x59A1D2A7A2E9C2A344123BFBAA7361F227E06863D3B1DCA5 PUSH5 0x736F6C6343 STOP ADDMOD SMOD STOP CALLER

internal virtual
PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x0 DUP1 REVERT INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 GASLIMIT 0xE7 GT 0xA8 PUSH15 0x800AE2D69D74D75BE4AE5CFEE813DB 0xBE 0xEA EXTCODECOPY 0xCB 0xF9 0xB3 0xD7 DUP3 PUSH15 0xA47FBD64736F6C6343000807003300

internal
PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x0 DUP1 REVERT INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 0xCA SWAP9 0xB8 SWAP16 PUSH21 0xC8C7289AA3263D3DA6B5C059D956AD938A0B30C0C3 SGT JUMPI 0x5E ADDMOD PUSH24 0x2364736F6C63430008070033000000000000000000000000

private
PUSH1 0x80 PUSH1 0x40 MSTORE PUSH1 0x0 DUP1 REVERT INVALID LOG2 PUSH5 0x6970667358 0x22 SLT KECCAK256 0x2D SWAP9 0x21 SAR SELFBALANCE CALLDATASIZE CODECOPY SWAP12 PUSH6 0x9810B3973BDC GT PUSH16 0xC918435C7C1C8DBEDDB6C72D8DEEA64 PUSH20 0x6F6C634300080700330000000000000000000000
```

2022-06-29 14:17 UTC, vrde requested changes

2022-06-29 14:17 UTC, vrde commented on contracts/ShareholderRegistry/ShareholderRegistryBase.sol
> +    mapping(address => bytes32) _statuses;
IMO it's more explicit if we still use `internal` here instead of using the default visibility, it makes more readable, what do you think?

2022-06-29 14:17 UTC, vrde commented on contracts/ShareholderRegistry/ShareholderRegistrySnapshot.sol
> +    TotalSupplySnapshots _totalSupplySnapshots;
Same here

2022-06-29 14:20 UTC, vrde requested changes
I think I've tagged all var definitions now

2022-06-29 14:20 UTC, vrde commented on contracts/ShareholderRegistry/ShareholderRegistryBase.sol
> +    mapping(address => bytes32) _statuses;
private → internal

2022-06-29 14:20 UTC, vrde commented on contracts/ShareholderRegistry/ShareholderRegistrySnapshot.sol
> -        private _accountStatusAndBalanceSnapshots;
Here

2022-06-29 14:20 UTC, vrde commented on contracts/TelediskoToken/TelediskoTokenSnapshot.sol
> +    mapping(address => Snapshots) _accountBalanceSnapshots;
private → internal

2022-06-29 14:20 UTC, vrde commented on contracts/TelediskoToken/TelediskoTokenSnapshot.sol
> +    Snapshots _totalSupplySnapshots;
private → internal

2022-06-29 14:20 UTC, vrde commented on contracts/Voting/VotingBase.sol
> +    bytes32 _contributorRole;
private → internal

2022-06-29 14:20 UTC, vrde commented on contracts/Voting/VotingSnapshot.sol
> +    SnapshotsValues _totalVotingPowerSnapshots;
private → internal

2022-06-30 08:45 UTC, vrde approved these changes
:1st_place_medal:

2022-06-30 08:45 UTC, merged