Add escrow contract
TelediskoDAO/contracts-legacy pull request #96
Opened 2022-10-26 14:14 UTC by vrde

Close #95

2022-11-01 12:10 UTC, sirnicolaz requested changes
A couple of minor issues, but overall good and simple solution. One missing piece is the deployment script for this type of contract.

2022-11-01 12:10 UTC, sirnicolaz commented on contracts/Escrow/Escrow.sol
> +    }
To make it more clear, would it be possible to rename things this way:
```
 function swap(address nativeTokenOwner, uint256 amount) public {
        _secondaryToken.transferFrom(_msgSender(), nativeTokenOwner, amount);
        _nativeToken.matchOffer(nativeTokenOwner, _msgSender(), amount);
}
```

The name of the method reflects better what the `Escrow` itself is actually doing and also avoid having the possibly confusing `transferFrom(_msgSender(), from, amount)`

2022-11-01 12:10 UTC, sirnicolaz commented on test/Escrow.ts
> +  });
Would it make sense add an "unhappy path" test?

2023-02-23 14:59 UTC, vrde commented
Replaced by #115

2023-02-23 15:00 UTC, closed without merging